In [148]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [149]:
df = pd.read_csv('stock_analysis.csv')

In [150]:

print(df.shape)
print(df.head())

(2509, 18)
      Symbol  0 Days Ago Price  2 Days Ago Price  5 Days Ago Price  \
0   HDFCBANK       1623.500000       1615.750000       1659.150024
1     ZOMATO        265.670013        256.290009        262.339996
2       ONGC        329.100006        310.250000        330.100006
3  ICICIBANK       1172.449951       1172.599976       1196.550049
4       HFCL        137.899994        124.459999        132.770004

   10 Days Ago Price  30 Days Ago Price  60 Days Ago Price  90 Days Ago Price  \
0        1605.050049        1635.349976        1561.300049        1447.500000
1         226.889999         207.929993         182.160004         195.250000
2         332.899994         299.149994         259.149994         265.250000
3        1212.699951        1235.050049        1123.800049        1115.699951
4         129.820007         131.289993          98.370003          93.199997

   180 Days Ago Price  365 Days Ago Price          LTP  2_day_rise  \
0         1403.599976         1649.900024  1623.500000    0.479653
1          149.449997           93.449997   265.670013    3.659918
2          267.549988          173.350006   329.100006    6.075747
3         1010.700012          979.900024  1172.449951   -0.012794
4          102.099998           70.199997   137.899994   10.798646

   5_day_rise  1_month_rise  2_month_rise  3_month_rise  6_month_rise  \
0   -2.148692     -0.724614      3.983856     12.158895     15.666859
1    1.269352     27.768972     45.844317     36.066588     77.765151
2   -0.302938     10.011704     26.992095     24.071633     23.005054
3   -2.014132     -5.068628      4.329053      5.086493     16.003754
4    3.863817      5.034657     40.185006     47.961372     35.063659

   1_year_rise
0    -1.600098
1   184.291088
2    89.847127
3    19.649956
4    96.438746

In [151]:

df.head()

# Identify rows with any 0 values
rows_with_zero = df.isin([0]).any(axis=1)

# Print the indices of rows with 0 values
print("Indices of rows with 0 values:", df[rows_with_zero].index.tolist())

# Drop rows with any 0 values
df = df[~rows_with_zero]

print(df.shape)
df['LTP'] = df['0 Days Ago Price']

Indices of rows with 0 values: [110, 204, 241, 271, 446, 636, 741, 1129, 1245, 1280, 1295, 1405, 1413, 1415, 1621, 1686, 1728, 1758, 1760, 1784, 1822, 1837, 1938, 1961, 2122, 2156, 2172, 2201, 2222, 2227, 2251, 2254, 2306, 2314, 2315, 2324, 2336, 2341, 2388, 2447, 2462, 2470, 2477, 2478, 2494, 2502]
(2463, 18)

In [ ]:
import yfinance as yf

def get_financial_metrics(ticker):
    # Fetch data for the ticker
    stock = yf.Ticker(ticker)
    
    # Fetch financial info
    info = stock.info
    
    # Extract required financial metrics
    return {
        'P/E Ratio (TTM)': info.get('trailingPE', None),
        'ROE': info.get('returnOnEquity', None),
        'Debt-to-Equity': info.get('debtToEquity', None),
        'Price-to-Book Ratio': info.get('priceToBook', None),
    }

def create_financial_dataframe(symbols):
    # Create an empty DataFrame with the desired columns
    df = pd.DataFrame(columns=['Symbol', 'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio'])
    
    # List to hold rows as dictionaries
    rows = []
    
    # Fetch and prepare financial metrics for each symbol
    for symbol in symbols:
        metrics = get_financial_metrics(symbol)
        metrics['Symbol'] = symbol
        rows.append(metrics)
        print(metrics)
    
    # Convert list of dictionaries to DataFrame
    df = pd.DataFrame(rows, columns=['Symbol', 'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio'])

    
    return df

In [152]:
df.head()

,Symbol,0 Days Ago Price,2 Days Ago Price,5 Days Ago Price,10 Days Ago Price,30 Days Ago Price,60 Days Ago Price,90 Days Ago Price,180 Days Ago Price,365 Days Ago Price,LTP,2_day_rise,5_day_rise,1_month_rise,2_month_rise,3_month_rise,6_month_rise,1_year_rise
0,HDFCBANK,1623.500000,1615.750000,1659.150024,1605.050049,1635.349976,1561.300049,1447.500000,1403.599976,1649.900024,1623.500000,0.479653,-2.148692,-0.724614,3.983856,12.158895,15.666859,-1.600098
1,ZOMATO,265.670013,256.290009,262.339996,226.889999,207.929993,182.160004,195.250000,149.449997,93.449997,265.670013,3.659918,1.269352,27.768972,45.844317,36.066588,77.765151,184.291088
2,ONGC,329.100006,310.250000,330.100006,332.899994,299.149994,259.149994,265.250000,267.549988,173.350006,329.100006,6.075747,-0.302938,10.011704,26.992095,24.071633,23.005054,89.847127
3,ICICIBANK,1172.449951,1172.599976,1196.550049,1212.699951,1235.050049,1123.800049,1115.699951,1010.700012,979.900024,1172.449951,-0.012794,-2.014132,-5.068628,4.329053,5.086493,16.003754,19.649956
4,HFCL,137.899994,124.459999,132.770004,129.820007,131.289993,98.370003,93.199997,102.099998,70.199997,137.899994,10.798646,3.863817,5.034657,40.185006,47.961372,35.063659,96.438746

In [ ]:
financial_df = pd.DataFrame(columns=['Symbol', 'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio'])
symbols = df['Symbol']+'.NS'
financial_df = create_financial_dataframe(symbols)
df['Symbol'] = df['Symbol']+'.NS'

In [153]:
df['Symbol'] = df['Symbol']+'.NS'
financial_df.head()

         Symbol  P/E Ratio (TTM)      ROE  Debt-to-Equity  Price-to-Book Ratio
0   HDFCBANK.NS        18.880960  0.17677             NaN             2.663429
1     ZOMATO.NS       381.739140      NaN           3.670            11.290668
2       ONGC.NS         9.356980      NaN          41.957             1.236221
3  ICICIBANK.NS        18.538181  0.18274             NaN             3.031949
4       HFCL.NS        54.360157      NaN          24.782             5.194406

In [154]:
df = pd.merge(df, financial_df, on='Symbol', how = 'outer')

In [155]:
df.head()

,Symbol,0 Days Ago Price,2 Days Ago Price,5 Days Ago Price,10 Days Ago Price,30 Days Ago Price,60 Days Ago Price,90 Days Ago Price,180 Days Ago Price,365 Days Ago Price,LTP,2_day_rise,5_day_rise,1_month_rise,2_month_rise,3_month_rise,6_month_rise,1_year_rise,P/E Ratio (TTM),ROE,Debt-to-Equity,Price-to-Book Ratio
0,HDFCBANK.NS,1623.500000,1615.750000,1659.150024,1605.050049,1635.349976,1561.300049,1447.500000,1403.599976,1649.900024,1623.500000,0.479653,-2.148692,-0.724614,3.983856,12.158895,15.666859,-1.600098,18.880960,0.17677,NaN,2.663429
1,ZOMATO.NS,265.670013,256.290009,262.339996,226.889999,207.929993,182.160004,195.250000,149.449997,93.449997,265.670013,3.659918,1.269352,27.768972,45.844317,36.066588,77.765151,184.291088,381.739140,NaN,3.670,11.290668
2,ONGC.NS,329.100006,310.250000,330.100006,332.899994,299.149994,259.149994,265.250000,267.549988,173.350006,329.100006,6.075747,-0.302938,10.011704,26.992095,24.071633,23.005054,89.847127,9.356980,NaN,41.957,1.236221
3,ICICIBANK.NS,1172.449951,1172.599976,1196.550049,1212.699951,1235.050049,1123.800049,1115.699951,1010.700012,979.900024,1172.449951,-0.012794,-2.014132,-5.068628,4.329053,5.086493,16.003754,19.649956,18.538181,0.18274,NaN,3.031949
4,HFCL.NS,137.899994,124.459999,132.770004,129.820007,131.289993,98.370003,93.199997,102.099998,70.199997,137.899994,10.798646,3.863817,5.034657,40.185006,47.961372,35.063659,96.438746,54.360157,NaN,24.782,5.194406

In [156]:
df['2_day_rise'] = -(df['2 Days Ago Price']-df['LTP'])*100/df['2 Days Ago Price']
df['5_day_rise'] = -(df['5 Days Ago Price'] - df['LTP'])*100/df['5 Days Ago Price']
df['10_day_rise'] = -(df['10 Days Ago Price']-df['LTP'])*100/df['10 Days Ago Price']
df['1_month_rise'] = -(df['30 Days Ago Price'] - df['LTP'])*100/df['30 Days Ago Price']
df['2_month_rise'] = -(df['60 Days Ago Price'] - df['LTP'])*100/df['60 Days Ago Price']
df['3_month_rise'] = -(df['90 Days Ago Price']-df['LTP'])*100/df['90 Days Ago Price']
df['6_month_rise'] = -(df['180 Days Ago Price']-df['LTP'])*100/df['180 Days Ago Price']
df['1_year_rise']= -(df['365 Days Ago Price']-df['LTP'])*100/df['365 Days Ago Price']

In [157]:
two_days_high_df = df.sort_values(by='2_day_rise', ascending=False)
five_days_high_df = df.sort_values(by='5_day_rise', ascending=False)
ten_days_high_df = df.sort_values(by='10_day_rise', ascending=False)
one_month_high_df = df.sort_values(by='1_month_rise', ascending=False)
two_month_high_df = df.sort_values(by='2_month_rise', ascending=False)
three_month_high_df = df.sort_values(by='3_month_rise', ascending=False)
six_month_high_df = df.sort_values(by='6_month_rise', ascending=False)
one_year_high_df = df.sort_values(by='1_year_rise', ascending=False)

In [158]:
cols = five_days_high_df.columns
print(cols)

Index(['Symbol', '0 Days Ago Price', '2 Days Ago Price', '5 Days Ago Price',
       '10 Days Ago Price', '30 Days Ago Price', '60 Days Ago Price',
       '90 Days Ago Price', '180 Days Ago Price', '365 Days Ago Price', 'LTP',
       '2_day_rise', '5_day_rise', '1_month_rise', '2_month_rise',
       '3_month_rise', '6_month_rise', '1_year_rise', 'P/E Ratio (TTM)', 'ROE',
       'Debt-to-Equity', 'Price-to-Book Ratio', '10_day_rise'],
      dtype='object')

In [159]:
cols_to_drop = ['0 Days Ago Price', '2 Days Ago Price',
       '5 Days Ago Price', '10 Days Ago Price',
       '30 Days Ago Price', '60 Days Ago Price', '90 Days Ago Price',
       '180 Days Ago Price', '365 Days Ago Price']

In [160]:
dfs = [two_days_high_df, five_days_high_df, ten_days_high_df, one_month_high_df, two_month_high_df, three_month_high_df, six_month_high_df, one_year_high_df]

for s in dfs:
    for col in cols_to_drop:
        s.drop(col, axis=1, inplace=True)

In [161]:
two_days_high_df.to_csv('two_days_high_df.csv')
five_days_high_df.to_csv('five_days_high_df.csv')
ten_days_high_df.to_csv('ten_days_high_df.csv')
one_month_high_df.to_csv('one_month_high_df.csv')
two_month_high_df.to_csv('two_month_high_df.csv')
three_month_high_df.to_csv('three_month_high_df.csv')
six_month_high_df.to_csv('six_month_high_df.csv')
one_year_high_df.to_csv('one_year_high_df.csv')

In [162]:
for df in dfs:
    print(df.columns)

Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')
Index(['Symbol', 'LTP', '2_day_rise', '5_day_rise', '1_month_rise',
       '2_month_rise', '3_month_rise', '6_month_rise', '1_year_rise',
       'P/E Ratio (TTM)', 'ROE', 'Debt-to-Equity', 'Price-to-Book Ratio',
       '10_day_rise'],
      dtype='object')

In [163]:
one_year_high_df[:100]

,Symbol,LTP,2_day_rise,5_day_rise,1_month_rise,2_month_rise,3_month_rise,6_month_rise,1_year_rise,P/E Ratio (TTM),ROE,Debt-to-Equity,Price-to-Book Ratio,10_day_rise
2427,WINSOME.NS,4.220000,-2.314824,-1.401879,14.363136,22.318833,15.616430,11.052627,2713.333082,NaN,NaN,NaN,NaN,6.030145
2003,DOLPHIN.NS,682.049988,1.790911,-2.046532,1.480436,-9.277734,11.500731,205.989236,2143.585514,41.728256,NaN,0.526,1.165272,3.899760
1503,KODYTECH.NS,3530.100098,-3.307449,-3.989881,-13.494902,47.486948,197.472002,245.986488,1877.647114,NaN,NaN,NaN,NaN,-11.719910
2338,SPYL.NS,7.200000,3.896104,5.882347,49.068321,81.360195,152.631581,206.382983,1500.000000,1.595652,NaN,11.606,34.786730,14.285708
1397,RBMINFRA.NS,639.250000,10.101624,17.931928,10.501296,40.401937,9.105645,-6.144469,1141.262136,NaN,NaN,NaN,NaN,41.114790
1581,SAHANA.NS,1406.750000,-1.975470,-6.874750,-21.395246,-7.148282,60.130905,37.512219,882.710485,NaN,NaN,NaN,NaN,-10.085970
2301,LGHL.NS,293.399994,3.328044,-1.560139,-12.587517,-12.885984,0.824740,62.099444,762.941159,1401.499900,0.245270,116.156,12.886170,0.462252
1722,ELECTHERM.NS,864.000000,-1.420505,-3.388123,19.139546,17.279759,12.514647,120.015272,741.695068,3.506303,NaN,NaN,NaN,-4.525113
904,SKYGOLD.NS,2027.500000,2.577721,-0.775686,4.886058,59.507516,60.778710,85.642994,694.163719,66.885155,0.236560,127.012,12.667997,-9.579452
1779,DIACABS.NS,1516.800049,-1.400847,-5.078376,22.091204,68.085107,70.503607,435.309693,677.846179,286.252350,NaN,NaN,NaN,11.578639
1013,TRIL.NS,710.549988,2.421620,-2.047151,-9.107773,-3.168438,23.670699,123.830512,623.574348,123.416820,NaN,45.453,17.739780,-5.868714
1612,KDL.NS,1685.250000,1.892442,-3.202183,3.618419,61.360586,76.891989,61.314260,616.822610,NaN,NaN,NaN,NaN,2.887759
9,COCHINSHIP.NS,2349.350098,-2.557026,-7.429363,-16.226281,24.094135,90.277006,166.170060,605.457590,71.668710,NaN,10.037,12.285461,-9.324760
1485,TECHLABS.NS,726.000000,3.234980,-1.891892,-18.778316,38.167282,102.425767,253.542721,604.512352,NaN,NaN,NaN,NaN,-7.279693
873,UNITECH.NS,10.210000,-1.161664,-6.158089,-13.839665,-0.777453,-2.761904,-36.187500,604.137911,NaN,NaN,NaN,NaN,-8.757816
928,V2RETAIL.NS,899.700012,-6.134584,-10.828088,21.065731,53.283924,100.982916,130.603621,592.076932,119.361040,NaN,191.280,12.120315,4.829597
1963,GRCL.NS,370.000000,0.721381,-3.896104,7.246377,3.641457,7.386450,85.000000,560.714286,NaN,NaN,NaN,NaN,-7.500000
901,NPST.NS,2910.899902,3.631315,8.133507,62.733747,93.775795,106.762081,132.890619,559.071691,NaN,NaN,NaN,NaN,6.542467
315,SHAKTIPUMP.NS,4654.750000,-4.525781,-0.682776,8.523836,85.966840,124.666350,217.513643,549.333913,61.042236,NaN,11.225,11.417038,6.995911
516,GET&D.NS,1758.550049,2.536369,0.632335,3.733965,26.994046,74.511266,113.286846,546.882475,150.760380,NaN,3.365,35.111090,11.710717
927,WEBELSOLAR.NS,701.500000,10.246741,15.759076,24.247260,15.236140,8.692280,46.374544,541.811510,NaN,NaN,170.460,32.631410,18.207092
1176,ORIANA.NS,2030.900024,10.249175,6.681729,-16.382576,-15.787942,-8.670231,145.901437,540.460418,NaN,NaN,NaN,NaN,-7.587645
1816,CROWN.NS,269.799988,-2.528902,-4.478677,-6.319449,16.811701,13.959868,82.915246,504.932729,53.988660,0.192570,80.001,8.270830,-6.530402
1421,RSSOFTWARE.NS,268.500000,2.657241,-2.078779,-4.295130,43.169462,12.437184,153.063152,495.343701,35.589622,0.510620,2.433,13.133159,0.618323
936,HUBTOWN.NS,278.320007,-2.766903,2.094576,60.526012,91.245798,112.701562,80.492875,479.833349,NaN,-0.065240,71.645,1.638421,20.203859
2076,ZODIAC.NS,705.750000,-3.959989,-5.881173,-6.299789,8.710719,22.931550,176.115017,469.842558,206.675610,0.262410,85.139,23.702500,-0.155617
592,WEL.NS,1496.300049,9.230943,8.956528,38.527058,57.588209,36.817082,365.629382,468.395080,208.157200,0.137720,73.496,31.101350,21.285573
2326,S&SPOWER.NS,364.100006,2.275283,0.330673,30.035716,56.132080,28.385049,74.419165,453.343449,53.364420,NaN,NaN,NaN,-0.844228
1252,E2E.NS,1653.099976,0.063553,-4.939622,-5.223024,-5.450700,49.264106,106.456844,453.061228,107.120930,NaN,203.284,36.323296,-4.964212
101,IFCI.NS,77.500000,2.296724,-5.395506,20.006190,27.572016,53.313553,25.000000,445.774655,132.982470,0.033600,70.070,4.127641,-7.018595
1524,MACPOWER.NS,1490.949951,3.491474,-1.009200,11.685831,2.189853,14.944875,52.083438,432.292010,63.435696,0.224830,0.403,12.920409,-4.597523
1847,DYNAMIC.NS,266.000000,-3.096539,1.740290,-3.884372,29.756098,-5.840708,105.246904,432.000000,NaN,NaN,NaN,NaN,1.314040
508,GMRP&UI.NS,99.029999,9.256398,5.362274,4.815829,39.008986,57.565634,88.449097,403.969469,NaN,NaN,NaN,NaN,2.483702
2331,ABCOTS.NS,220.500000,5.000000,0.227273,-6.607372,-10.728745,-26.986755,-14.567999,400.000017,NaN,NaN,NaN,NaN,1.612903
1753,TIRUPATI.NS,719.000000,-1.236264,-1.236264,-6.919543,35.404896,41.535433,51.944206,395.862069,NaN,NaN,NaN,NaN,-6.495872
1333,TARACHAND.NS,404.149994,4.647846,-0.578107,-13.854844,-4.161731,-3.922501,139.142008,392.265532,39.399296,NaN,89.817,6.719296,-12.757692
1873,VIVIANA.NS,812.000000,-1.096224,-5.974986,-22.087887,24.263522,41.611435,136.321300,392.121212,NaN,NaN,NaN,NaN,2.570577
1442,SPMLINFRA.NS,194.199997,10.234432,4.718253,0.403267,37.769571,50.717880,72.239465,382.484464,NaN,NaN,506.681,3.010556,-1.084911
1311,OWAIS.NS,1264.000000,0.717131,-0.441082,-9.361446,-2.981922,42.030449,381.523810,381.523810,NaN,NaN,NaN,NaN,-2.000314
1237,PURVA.NS,482.450012,-2.712237,-0.474469,-3.750621,13.158205,37.274149,106.616708,372.064605,148.571430,NaN,175.988,6.000000,3.931495
1155,SBGLP.NS,117.129997,2.520785,-1.711841,-9.510202,-4.586188,0.282529,50.989368,365.540532,718.750000,0.775220,63.749,34.472424,-4.023274
1766,URBAN.NS,429.500000,-1.659989,-0.278619,11.399303,32.930979,15.348461,27.827381,363.572577,NaN,NaN,NaN,NaN,-2.208564
26,RVNL.NS,565.799988,2.723312,-4.069176,-0.017677,51.303642,116.740094,118.244933,356.658580,82.635720,NaN,68.976,13.817362,-6.679862
2270,21STCENMGM.NS,91.570000,4.033178,6.106601,22.174788,77.771312,81.686502,109.542330,348.872556,1.717822,NaN,NaN,1.915238,14.821316
1676,INDOTECH.NS,2011.199951,-9.748929,-14.260136,16.066476,23.435725,45.559819,101.180347,346.437281,38.710373,NaN,2.302,8.777248,2.437160
2367,PARASPETRO.NS,3.770000,-1.822915,-3.826533,-3.826533,1.617249,10.882349,39.629626,343.529397,NaN,NaN,NaN,6.552963,-14.512469
2157,GIRIRAJ.NS,374.899994,4.124429,-1.081796,-11.371160,-21.388132,-15.544042,-46.412235,341.890630,NaN,NaN,NaN,NaN,8.982556
98,HUDCO.NS,298.500000,2.877824,-2.514700,-10.373814,11.672283,39.290712,49.138151,333.551208,28.643667,0.132060,445.421,3.649270,-5.865659
1380,ESSARSHPNG.NS,48.209999,-0.186336,-4.021502,-9.037738,28.559998,75.628407,62.596964,330.446428,NaN,NaN,NaN,NaN,-15.168049
2416,TCIFINANCE.NS,13.420000,-6.999308,-11.652400,-22.067360,40.523558,111.338587,163.137261,326.031736,NaN,NaN,NaN,NaN,7.188495
1121,JAIBALAJI.NS,892.400024,2.011893,-2.063212,-2.645503,3.671008,-3.753234,-12.995996,325.763358,17.807154,NaN,31.416,10.076705,-3.763611
43,IREDA.NS,248.250000,3.913774,-2.455796,0.758988,39.036682,50.637133,38.223826,313.750000,49.579160,NaN,582.923,7.768636,-6.676444
1415,GRPLTD.NS,3618.037598,-0.197228,-3.455275,3.403525,38.075913,114.146844,183.734269,313.183064,80.146370,NaN,67.882,2.999396,-5.379552
894,GPTINFRA.NS,165.649994,3.518304,-1.574575,0.546279,36.230924,60.048303,81.087725,310.787330,35.264187,NaN,64.050,6.927305,-2.673327
1723,LEMERITE.NS,192.350006,0.286759,-0.388400,31.341762,91.966080,159.231825,227.404266,306.230227,NaN,NaN,NaN,NaN,1.664910
1628,EIMCOELECO.NS,3002.300049,1.533678,-1.573616,15.178492,51.539477,51.965177,101.516938,303.047382,37.702900,NaN,0.106,4.600641,-9.211039
1021,WEALTH.NS,1299.900024,-12.438114,-6.837241,56.012963,57.831479,40.105631,179.879425,301.575525,30.257242,NaN,NaN,10.914414,35.561580
1246,NITCO.NS,74.970001,-4.056819,-6.811679,-2.293760,4.516935,-3.575561,43.758387,299.840007,NaN,NaN,NaN,NaN,3.506835
2266,KAVVERITEL.NS,32.459999,-3.992908,-5.940305,33.910889,111.741678,70.842100,96.727267,298.282216,NaN,-0.026890,NaN,1.306692,1.755484
1183,WANBURY.NS,195.979996,-4.016063,-8.816823,21.961536,29.317052,43.785760,20.233126,292.352338,11.633137,5.136599,416.889,23.021078,-9.226493
699,MARINE.NS,268.049988,-0.241915,-5.232462,35.921089,145.018267,190.097385,140.188164,288.196924,150.746280,0.109560,37.979,15.785361,13.177669
2391,LCCINFOTEC.NS,6.460000,3.858525,5.901642,48.505751,111.111116,240.000006,111.803283,279.999992,NaN,-1.830600,118.825,39.310350,14.134279
1636,SIMPLEXINF.NS,130.490005,-5.722128,-10.439253,-15.627827,1.045382,5.276328,44.988895,278.231900,NaN,-0.269970,3077.289,3.720861,-8.837498
52,SUZLON.NS,69.580002,2.549747,-2.480724,26.050726,46.793248,75.707082,46.948266,274.086024,125.562500,NaN,3.832,27.417265,7.079099
892,OMINFRAL.NS,215.949997,-0.254043,-5.243527,22.824473,69.532110,73.802814,54.525937,271.686751,41.739132,NaN,13.985,2.693187,0.208815
2359,GKWLIMITED.NS,3313.800049,2.106028,-1.817693,2.095015,40.139140,43.609970,91.041168,270.029601,157.773930,0.006070,0.001,0.922185,-3.914405
394,GTLINFRA.NS,2.770000,1.465200,-3.819449,-29.336737,48.128341,78.709682,15.416661,269.333331,NaN,NaN,NaN,NaN,-7.357860
38,GRSE.NS,2178.949951,-1.418364,-6.346176,-16.215176,64.449053,141.930816,150.828816,268.159169,76.703420,NaN,3.924,13.811730,-6.215169
2119,RMDRIP.NS,177.000000,3.448272,1.929171,12.738854,25.576448,34.294382,70.028821,267.983380,NaN,NaN,NaN,NaN,4.795741
2340,BLUECHIP.NS,5.870000,-4.084967,-6.080002,24.893620,77.341389,77.878787,130.196078,266.874987,NaN,-0.861350,NaN,18.741497,-2.491696
1327,KRITIKA.NS,19.930000,7.208177,1.839553,-3.766291,1.476583,-15.550848,38.402784,263.465066,48.692310,0.131330,47.539,6.005693,4.018792
21,IRFC.NS,182.410004,1.689151,-5.157801,-9.706960,5.433217,24.046243,18.679250,262.644148,37.993893,0.136630,841.671,4.957349,-6.585753
751,KPIGREEN.NS,965.950012,-0.999283,-4.370851,5.208987,7.405353,3.826521,36.784592,261.959782,65.899450,NaN,124.027,15.696684,2.766105
990,MINDTECK.NS,431.350006,5.322920,-1.641770,29.224093,45.235692,44.095539,89.188599,259.458338,37.931840,NaN,1.000,4.619942,0.150916
1027,VISHNUINFR.NS,274.549988,15.357138,18.596107,6.476626,57.832706,20.074347,-6.424678,258.186539,NaN,NaN,NaN,NaN,13.614730
115,NBCC.NS,171.300003,2.043253,-5.775577,-10.422001,19.823723,31.214093,15.782363,255.025913,81.674100,0.182680,0.026,14.718423,-8.688701
2219,MANAKCOAT.NS,61.580002,-2.547866,-5.450630,0.950823,-11.268011,16.628793,91.242237,254.927957,37.724552,NaN,118.174,2.788968,-3.796282
627,TECHNOE.NS,1650.500000,1.572359,-3.504923,10.331231,29.303934,64.893349,107.011166,254.603063,67.208565,0.132420,NaN,8.432584,0.015149
1932,SWARAJ.NS,342.000000,2.764427,-1.639348,17.667300,67.647059,58.921935,182.411234,254.404145,NaN,NaN,NaN,NaN,8.536970
1426,KRISHNADEF.NS,702.000000,0.486691,-4.535252,-20.919231,-2.377969,71.995592,95.000000,251.879699,NaN,NaN,NaN,NaN,-12.266453
2153,GLOBALVECT.NS,274.950012,-3.947594,-5.871275,27.262212,36.383930,40.675373,119.083675,251.373818,327.411740,0.048340,2371.928,17.868378,-6.966907
1556,GALLANTT.NS,296.799988,-2.013868,-4.780245,-12.319058,2.098375,9.763312,42.658007,250.206475,36.856224,0.096390,18.848,3.381838,-5.326958
2321,KARNIKA.NS,288.000000,1.034910,-3.177009,-5.263158,2.491103,-9.148265,108.998544,248.668287,NaN,NaN,NaN,NaN,-3.517588
632,WOCKPHARMA.NS,890.150024,2.339623,-1.033964,1.118941,55.988782,67.668108,94.122789,246.025277,NaN,NaN,64.336,4.583865,4.705052
1159,ASHIMASYN.NS,44.080002,8.278071,3.135237,-3.481490,16.490491,122.065496,87.176235,244.375009,7.307543,NaN,39.102,2.285265,-1.694912
25,MTNL.NS,70.070000,-1.766441,-6.685307,65.025910,85.763514,103.396221,45.979166,244.324316,NaN,NaN,NaN,NaN,-24.018652
451,WALCHANNAG.NS,395.950012,-0.251921,-5.229769,25.566876,86.716032,113.622875,82.423408,242.517316,NaN,NaN,66.573,5.950190,4.208343
469,ELECTCAST.NS,204.589996,3.568899,-4.855138,11.045370,22.803115,19.294459,10.949026,242.123744,14.496593,NaN,45.600,2.547616,-2.608659
658,RTNPOWER.NS,16.360001,-0.486618,-5.488151,-0.061089,-4.327484,43.508782,48.727278,240.833333,0.893581,NaN,81.622,1.952990,-0.788352
5,OIL.NS,617.799988,7.322151,1.947193,23.547646,52.606004,50.109330,79.540824,238.644245,16.083761,NaN,45.682,2.209906,6.443825
1560,TGL.NS,444.399994,6.737117,1.403307,-15.312055,30.552292,101.816530,238.590472,238.590472,NaN,NaN,NaN,NaN,-9.518477
1069,RPPINFRA.NS,209.279999,1.879077,-0.262118,46.002514,76.428928,85.121622,37.008183,235.116087,14.411022,0.144720,9.635,1.935659,6.775510
466,DOLATALGO.NS,150.050003,6.358095,1.064189,13.760432,3.589918,17.455971,72.669736,233.815352,13.068404,NaN,10.605,3.562580,8.826514
2438,TVVISION.NS,8.080000,-0.246919,-2.060607,6.176081,14.609925,71.914899,28.253963,229.795909,NaN,NaN,NaN,NaN,-6.155630
403,PCJEWELLER.NS,90.029999,-0.265867,-5.261496,60.309827,64.588661,83.922364,71.812970,229.177322,NaN,-0.190080,141.587,1.440450,5.731060
1831,ZEELEARN.NS,10.990000,2.614377,5.774778,41.806449,51.586204,83.166663,56.999997,228.059704,2.070140,0.962780,196.880,1.845632,23.068302
2347,ATLANTAA.NS,46.660000,-3.991767,-5.927417,13.197473,24.826106,54.247933,96.050426,227.438595,0.697428,NaN,151.464,2.380706,-0.469286
2095,THOMASCOTT.NS,236.350006,-0.105664,-4.175953,-15.286736,-3.214575,-6.154457,-23.770355,227.128036,26.713867,0.308200,11.632,7.449821,-13.026677
1393,DPABHUSHAN.NS,1232.800049,1.804377,-2.189779,-9.075482,-2.783686,10.853347,65.310097,226.483059,37.693146,NaN,73.264,11.274436,-5.048710
1942,HMT.NS,89.500000,-2.281905,-7.176932,23.244281,57.876172,69.347214,31.714502,223.688974,NaN,NaN,NaN,NaN,6.105515

In [ ]:
import requests

api_key = 'ehgNGm4fEF9YXjPaRcEcMqNzNBqfGtbt'

# List of symbols you want to fetch data for

# Construct the URL for the bulk request
url = f'https://financialmodelingprep.com/api/v4/key-metrics-ttm-bulk?tickers={",".join(symbols)}&apikey={api_key}'

# Send the request to the API
response = requests.get(url)

# Check if the request was successful
if response.status_code == 200:
    data = response.json()
    
    # Create lists to store data for DataFrame
    symbols_list = []
    pe_ratios = []
    roes = []
    debt_to_equities = []
    pb_ratios = []

    # Loop through the response data and populate lists
    for company_data in data:
        symbol = company_data.get('symbol')
        pe_ratio = company_data.get('peRatioTTM')
        roe = company_data.get('roeTTM')
        debt_to_equity = company_data.get('debtToEquityRatioTTM')
        pb_ratio = company_data.get('pbRatioTTM')

        symbols_list.append(symbol)
        pe_ratios.append(pe_ratio)
        roes.append(roe)
        debt_to_equities.append(debt_to_equity)
        pb_ratios.append(pb_ratio)
    
    # Create a DataFrame from the lists
    metrics_df = pd.DataFrame({
        'Symbol': symbols_list,
        'P/E Ratio': pe_ratios,
        'ROE': roes,
        'Debt-to-Equity Ratio': debt_to_equities,
        'P/B Ratio': pb_ratios
    })

    print(df)
else:
    print("Error fetching data:", response.status_code)

In [ ]:
def fetch_data_in_batches(symbols, api_key, batch_size=10):
    url_base = 'https://financialmodelingprep.com/api/v4/key-metrics-ttm-bulk?tickers='
    headers = {'apikey': api_key}
    
    # List to store all data
    all_data = []

    # Process symbols in batches
    for i in range(0, len(symbols), batch_size):
        batch = symbols[i:i + batch_size]
        url = f'{url_base}{",".join(batch)}&apikey={api_key}'
        response = requests.get(url)
        
        if response.status_code == 200:
            data = response.json()
            all_data.extend(data)
        else:
            print(f"Error fetching data for batch starting with {batch[0]}: {response.status_code}")
    
    return all_data

# Fetch data for the symbols
data = fetch_data_in_batches(symbols, api_key)

# Create lists to store data for DataFrame
symbols_list = []
pe_ratios = []
roes = []
debt_to_equities = []
pb_ratios = []

# Process the fetched data
for company_data in data:
    symbol = company_data.get('symbol')
    pe_ratio = company_data.get('peRatioTTM')
    roe = company_data.get('roeTTM')
    debt_to_equity = company_data.get('debtToEquityRatioTTM')
    pb_ratio = company_data.get('pbRatioTTM')

    symbols_list.append(symbol)
    pe_ratios.append(pe_ratio)
    roes.append(roe)
    debt_to_equities.append(debt_to_equity)
    pb_ratios.append(pb_ratio)

# Create a DataFrame from the lists
metrics_df = pd.DataFrame({
    'Symbol': symbols_list,
    'P/E Ratio': pe_ratios,
    'ROE': roes,
    'Debt-to-Equity Ratio': debt_to_equities,
    'P/B Ratio': pb_ratios
})

print(metrics_df)

In [ ]:
import requests
import pandas as pd

# Your FMP API key
api_key = 'ehgNGm4fEF9YXjPaRcEcMqNzNBqfGtbt'

# List of symbols you want to fetch data for
symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'FB']

# Function to get financial metrics in batches
def fetch_data_in_batches(symbols, api_key, batch_size=10):
    url_base = 'https://financialmodelingprep.com/api/v4/key-metrics-ttm-bulk?tickers='
    headers = {'apikey': api_key}
    
    # List to store all data
    all_data = []

    # Process symbols in batches
    for i in range(0, len(symbols), batch_size):
        batch = symbols[i:i + batch_size]
        url = f'{url_base}{",".join(batch)}&apikey={api_key}'
        response = requests.get(url)
        
        if response.status_code == 200:
            data = response.json()
            if isinstance(data, list):
                all_data.extend(data)
            else:
                print(f"Unexpected data format for batch starting with {batch[0]}: {data}")
        else:
            print(f"Error fetching data for batch starting with {batch[0]}: {response.status_code}")
    
    return all_data

# Fetch data for the symbols
data = fetch_data_in_batches(symbols, api_key)

# Create lists to store data for DataFrame
symbols_list = []
pe_ratios = []
roes = []
debt_to_equities = []
pb_ratios = []

# Process the fetched data
for company_data in data:
    symbol = company_data.get('symbol', 'N/A')
    pe_ratio = company_data.get('peRatioTTM', 'N/A')
    roe = company_data.get('roeTTM', 'N/A')
    debt_to_equity = company_data.get('debtToEquityRatioTTM', 'N/A')
    pb_ratio = company_data.get('pbRatioTTM', 'N/A')

    symbols_list.append(symbol)
    pe_ratios.append(pe_ratio)
    roes.append(roe)
    debt_to_equities.append(debt_to_equity)
    pb_ratios.append(pb_ratio)

# Create a DataFrame from the lists
metrics_df = pd.DataFrame({
    'Symbol': symbols_list,
    'P/E Ratio': pe_ratios,
    'ROE': roes,
    'Debt-to-Equity Ratio': debt_to_equities,
    'P/B Ratio': pb_ratios
})

print(metrics_df)